In [1]:
import pandas as pd
import numpy as np

# Importing the data and exploring it

## Importing cancer data

In [2]:
cancer_data = pd.read_csv("./data_clean/cancer_by_type.csv")
cancer_data.head()

,locale,fips,met_health_obj,incidence rate_per_100000,incidence rate_lower_95_confidence,incidence rate_upper_95_confidence,annual_count_avg,recent_trend_str,trend_last_5,trend_last_5_lower_95_confidence,...,cancer,file_name,race,sex,source_url,stage,stateFIPS,type,state,cancer_description
0,"US (SEER+NPCR)(1,10)",0.0,***,448.0,447.7,448.4,1638110.0,falling,-0.9,-1.6,...,1,incidencerates_000.csv,0,0,https://www.statecancerprofiles.cancer.gov/inc...,NaN,29,incd,missouri,All Cancer Sites
1,"US (SEER+NPCR)(1,10)",0.0,***,448.0,447.7,448.4,1638110.0,falling,-0.9,-1.6,...,1,incidencerates_000.csv,0,0,https://www.statecancerprofiles.cancer.gov/inc...,NaN,46,incd,southdakota,All Cancer Sites
2,"US (SEER+NPCR)(1,10)",0.0,***,448,447.7,448.4,1638110,falling,-0.9,-1.6,...,1,incidencerates_000.csv,0,0,https://www.statecancerprofiles.cancer.gov/inc...,NaN,2,incd,alaska,All Cancer Sites
3,"US (SEER+NPCR)(1,10)",0.0,***,448.0,447.7,448.4,1638110.0,falling,-0.9,-1.6,...,1,incidencerates_000.csv,0,0,https://www.statecancerprofiles.cancer.gov/inc...,NaN,33,incd,newhampshire,All Cancer Sites
4,"US (SEER+NPCR)(1,10)",0.0,***,448.0,447.7,448.4,1638110.0,falling,-0.9,-1.6,...,1,incidencerates_000.csv,0,0,https://www.statecancerprofiles.cancer.gov/inc...,NaN,17,incd,illinois,All Cancer Sites

In [3]:
cancer_data.columns

Index(['locale', 'fips', 'met_health_obj', 'incidence rate_per_100000',
       'incidence rate_lower_95_confidence',
       'incidence rate_upper_95_confidence', 'annual_count_avg',
       'recent_trend_str', 'trend_last_5', 'trend_last_5_lower_95_confidence',
       'trend_last_5_upper_95_confidence', 'age', 'areatype', 'cancer',
       'file_name', 'race', 'sex', 'source_url', 'stage', 'stateFIPS', 'type',
       'state', 'cancer_description'],
      dtype='object')

In [4]:
cancer_data = cancer_data[['locale', 'fips', 'areatype', 'cancer', 'stateFIPS',
       'state', 'cancer_description', 'annual_count_avg', 'incidence rate_per_100000',
        'incidence rate_lower_95_confidence', 'incidence rate_upper_95_confidence']]
cancer_data.head()

,locale,fips,areatype,cancer,stateFIPS,state,cancer_description,annual_count_avg,incidence rate_per_100000,incidence rate_lower_95_confidence,incidence rate_upper_95_confidence
0,"US (SEER+NPCR)(1,10)",0.0,country,1,29,missouri,All Cancer Sites,1638110.0,448.0,447.7,448.4
1,"US (SEER+NPCR)(1,10)",0.0,country,1,46,southdakota,All Cancer Sites,1638110.0,448.0,447.7,448.4
2,"US (SEER+NPCR)(1,10)",0.0,country,1,2,alaska,All Cancer Sites,1638110,448,447.7,448.4
3,"US (SEER+NPCR)(1,10)",0.0,country,1,33,newhampshire,All Cancer Sites,1638110.0,448.0,447.7,448.4
4,"US (SEER+NPCR)(1,10)",0.0,country,1,17,illinois,All Cancer Sites,1638110.0,448.0,447.7,448.4

In [5]:
cancer_data.tail()

,locale,fips,areatype,cancer,stateFIPS,state,cancer_description,annual_count_avg,incidence rate_per_100000,incidence rate_lower_95_confidence,incidence rate_upper_95_confidence
74492,"Weston County(6,10)",56045.0,county,86,56,wyoming,Non-Hodgkin Lymphoma,3 or fewer,*,*,*
74493,"Weston County(6,10)",56045.0,county,90,56,wyoming,Leukemia,3 or fewer,*,*,*
74494,"Weston County(6,10)",56045.0,county,400,56,wyoming,Breast (in situ) (Female),3 or fewer,*,*,*
74495,"Weston County(6,10)",56045.0,county,515,56,wyoming,"Childhood (Ages <20, All Sites)",3 or fewer,*,*,*
74496,"Weston County(6,10)",56045.0,county,516,56,wyoming,"Childhood (Ages <15, All Sites)",3 or fewer,*,*,*

In [6]:
cancer_data

,locale,fips,areatype,cancer,stateFIPS,state,cancer_description,annual_count_avg,incidence rate_per_100000,incidence rate_lower_95_confidence,incidence rate_upper_95_confidence
0,"US (SEER+NPCR)(1,10)",0.0,country,1,29,missouri,All Cancer Sites,1638110.0,448.0,447.7,448.4
1,"US (SEER+NPCR)(1,10)",0.0,country,1,46,southdakota,All Cancer Sites,1638110.0,448.0,447.7,448.4
2,"US (SEER+NPCR)(1,10)",0.0,country,1,2,alaska,All Cancer Sites,1638110,448,447.7,448.4
3,"US (SEER+NPCR)(1,10)",0.0,country,1,33,newhampshire,All Cancer Sites,1638110.0,448.0,447.7,448.4
4,"US (SEER+NPCR)(1,10)",0.0,country,1,17,illinois,All Cancer Sites,1638110.0,448.0,447.7,448.4
...,...,...,...,...,...,...,...,...,...,...,...
74492,"Weston County(6,10)",56045.0,county,86,56,wyoming,Non-Hodgkin Lymphoma,3 or fewer,*,*,*
74493,"Weston County(6,10)",56045.0,county,90,56,wyoming,Leukemia,3 or fewer,*,*,*
74494,"Weston County(6,10)",56045.0,county,400,56,wyoming,Breast (in situ) (Female),3 or fewer,*,*,*
74495,"Weston County(6,10)",56045.0,county,515,56,wyoming,"Childhood (Ages <20, All Sites)",3 or fewer,*,*,*
74496,"Weston County(6,10)",56045.0,county,516,56,wyoming,"Childhood (Ages <15, All Sites)",3 or fewer,*,*,*

### Dealing with non-numerical values

In [7]:
cancer_data.replace(to_replace=['3 or fewer', 'ï¿½'], value='0', inplace=True)
cancer_data['annual_count_avg'] = cancer_data['annual_count_avg'].astype("float64").astype("int64")

In [8]:
def split_keep_first(text):
    return text.split()[0]

In [9]:
cancer_data['incidence rate_per_100000'] = cancer_data['incidence rate_per_100000'].apply(split_keep_first)
cancer_data['incidence rate_lower_95_confidence'] = cancer_data['incidence rate_lower_95_confidence'].apply(split_keep_first)
cancer_data['incidence rate_upper_95_confidence'] = cancer_data['incidence rate_upper_95_confidence'].apply(split_keep_first)

In [10]:
cancer_data.replace(to_replace=['* ', '*', 'ï¿½'], value='0', inplace=True)

In [11]:
cancer_data['incidence rate_per_100000'] = cancer_data['incidence rate_per_100000'].astype("float64")
cancer_data['incidence rate_lower_95_confidence'] = cancer_data['incidence rate_lower_95_confidence'].astype("float64")
cancer_data['incidence rate_upper_95_confidence'] = cancer_data['incidence rate_upper_95_confidence'].astype("float64")

In [12]:
cancer_data.head()

,locale,fips,areatype,cancer,stateFIPS,state,cancer_description,annual_count_avg,incidence rate_per_100000,incidence rate_lower_95_confidence,incidence rate_upper_95_confidence
0,"US (SEER+NPCR)(1,10)",0.0,country,1,29,missouri,All Cancer Sites,1638110,448.0,447.7,448.4
1,"US (SEER+NPCR)(1,10)",0.0,country,1,46,southdakota,All Cancer Sites,1638110,448.0,447.7,448.4
2,"US (SEER+NPCR)(1,10)",0.0,country,1,2,alaska,All Cancer Sites,1638110,448.0,447.7,448.4
3,"US (SEER+NPCR)(1,10)",0.0,country,1,33,newhampshire,All Cancer Sites,1638110,448.0,447.7,448.4
4,"US (SEER+NPCR)(1,10)",0.0,country,1,17,illinois,All Cancer Sites,1638110,448.0,447.7,448.4

In [13]:
cancer_data

,locale,fips,areatype,cancer,stateFIPS,state,cancer_description,annual_count_avg,incidence rate_per_100000,incidence rate_lower_95_confidence,incidence rate_upper_95_confidence
0,"US (SEER+NPCR)(1,10)",0.0,country,1,29,missouri,All Cancer Sites,1638110,448.0,447.7,448.4
1,"US (SEER+NPCR)(1,10)",0.0,country,1,46,southdakota,All Cancer Sites,1638110,448.0,447.7,448.4
2,"US (SEER+NPCR)(1,10)",0.0,country,1,2,alaska,All Cancer Sites,1638110,448.0,447.7,448.4
3,"US (SEER+NPCR)(1,10)",0.0,country,1,33,newhampshire,All Cancer Sites,1638110,448.0,447.7,448.4
4,"US (SEER+NPCR)(1,10)",0.0,country,1,17,illinois,All Cancer Sites,1638110,448.0,447.7,448.4
...,...,...,...,...,...,...,...,...,...,...,...
74492,"Weston County(6,10)",56045.0,county,86,56,wyoming,Non-Hodgkin Lymphoma,0,0.0,0.0,0.0
74493,"Weston County(6,10)",56045.0,county,90,56,wyoming,Leukemia,0,0.0,0.0,0.0
74494,"Weston County(6,10)",56045.0,county,400,56,wyoming,Breast (in situ) (Female),0,0.0,0.0,0.0
74495,"Weston County(6,10)",56045.0,county,515,56,wyoming,"Childhood (Ages <20, All Sites)",0,0.0,0.0,0.0
74496,"Weston County(6,10)",56045.0,county,516,56,wyoming,"Childhood (Ages <15, All Sites)",0,0.0,0.0,0.0

In [14]:
# converting type of "fips" to int64
cancer_data['fips'] = cancer_data['fips'].astype("int64")

In [15]:
# number of fips codes for which cancer data is available
len(cancer_data['fips'].unique())

3190

## Importing industry data per county

In [16]:
industry_data = pd.read_csv("./data_clean/final_indicators_per-industry_per-county.csv")
industry_data.head()

,Unnamed: 0,fips,county,name,industry_code,industry_detail,relevant_naics,year,payann,total_compensation,...,METL,MINE,MSW,NREN,OZON,PEST,REN,SMOG,VADD,WATR
0,0,8001,1,"Adams County, Colorado",113000,timber and raw forest products,[113],2012,0.00,6363.0,...,0,0,0,0,0,0,0,0,0,0
1,1,8001,1,"Adams County, Colorado",115000,agriculture and forestry support,[115],2012,0.29,12285.0,...,1.04547E-07,0,0.00446732,0,2.3968E-07,1.15031E-05,0.001257678,0.002638694,0.277337331,0.020533673
2,2,8001,1,"Adams County, Colorado",211000,unrefined oil and gas,[211],2012,0.00,34979.0,...,0,0,0,0,0,0,0,0,0,0
3,3,8001,1,"Adams County, Colorado",2122a0,"iron, gold, silver, and other metal ores","[21221, 21222, 21229]",2012,0.00,2670.0,...,0,0,0,0,0,0,0,0,0,0
4,4,8001,1,"Adams County, Colorado",212310,dimensional stone,[21231],2012,0.00,2385.0,...,0,0,0,0,0,0,0,0,0,0

In [17]:
industry_data.columns

Index(['Unnamed: 0', 'fips', 'county', 'name', 'industry_code',
       'industry_detail', 'relevant_naics', 'year', 'payann',
       'total_compensation', 'added_value ($)', 'Local_tranforrmation_ind',
       'estab', 'emp', 'ACID', 'ENRG', 'ETOX', 'EUTR', 'FOOD', 'GCC', 'HAPS',
       'HAZW', 'HC', 'HNC', 'HRSP', 'HTOX', 'JOBS', 'LAND', 'METL', 'MINE',
       'MSW', 'NREN', 'OZON', 'PEST', 'REN', 'SMOG', 'VADD', 'WATR'],
      dtype='object')

### Removing un-necessary columns

In [18]:
industry_data.drop('Unnamed: 0', axis=1, inplace=True)

In [19]:
def remove_useless(df):
    for col in df.columns:
        if len(df[col].unique()) == 1:
            df.drop(col, axis=1, inplace=True)

In [20]:
remove_useless(industry_data)
industry_data.columns

Index(['fips', 'county', 'name', 'industry_code', 'industry_detail',
       'relevant_naics', 'payann', 'total_compensation', 'added_value ($)',
       'Local_tranforrmation_ind', 'estab', 'emp', 'ACID', 'ENRG', 'ETOX',
       'EUTR', 'FOOD', 'GCC', 'HAPS', 'HAZW', 'HC', 'HNC', 'HRSP', 'HTOX',
       'JOBS', 'LAND', 'METL', 'MINE', 'MSW', 'NREN', 'OZON', 'PEST', 'REN',
       'SMOG', 'VADD', 'WATR'],
      dtype='object')

### Renaming some columns

In [21]:
industry_data = industry_data.rename(columns={'Local_tranforrmation_ind': 'local_tranformation_ind'})

### Dealing with non-numerical values

In [22]:
industry_data.replace(to_replace=['#DIV/0!'], value='0', inplace=True)
industry_data['local_tranformation_ind'] = industry_data['local_tranformation_ind'].astype("float64")

In [23]:
industry_data.head()

,fips,county,name,industry_code,industry_detail,relevant_naics,payann,total_compensation,added_value ($),local_tranformation_ind,...,METL,MINE,MSW,NREN,OZON,PEST,REN,SMOG,VADD,WATR
0,8001,1,"Adams County, Colorado",113000,timber and raw forest products,[113],0.00,6363.0,8448,0.00000,...,0,0,0,0,0,0,0,0,0,0
1,8001,1,"Adams County, Colorado",115000,agriculture and forestry support,[115],0.29,12285.0,16115,0.00038,...,1.04547E-07,0,0.00446732,0,2.3968E-07,1.15031E-05,0.001257678,0.002638694,0.277337331,0.020533673
2,8001,1,"Adams County, Colorado",211000,unrefined oil and gas,[211],0.00,34979.0,209735,0.00000,...,0,0,0,0,0,0,0,0,0,0
3,8001,1,"Adams County, Colorado",2122a0,"iron, gold, silver, and other metal ores","[21221, 21222, 21229]",0.00,2670.0,10099,0.00000,...,0,0,0,0,0,0,0,0,0,0
4,8001,1,"Adams County, Colorado",212310,dimensional stone,[21231],0.00,2385.0,8559,0.00000,...,0,0,0,0,0,0,0,0,0,0

In [24]:
industry_data

,fips,county,name,industry_code,industry_detail,relevant_naics,payann,total_compensation,added_value ($),local_tranformation_ind,...,METL,MINE,MSW,NREN,OZON,PEST,REN,SMOG,VADD,WATR
0,8001,1,"Adams County, Colorado",113000,timber and raw forest products,[113],0.000,6363.0,8448,0.000000,...,0,0,0,0,0,0,0,0,0,0
1,8001,1,"Adams County, Colorado",115000,agriculture and forestry support,[115],0.290,12285.0,16115,0.000380,...,1.04547E-07,0,0.00446732,0,2.3968E-07,1.15031E-05,0.001257678,0.002638694,0.277337331,0.020533673
2,8001,1,"Adams County, Colorado",211000,unrefined oil and gas,[211],0.000,34979.0,209735,0.000000,...,0,0,0,0,0,0,0,0,0,0
3,8001,1,"Adams County, Colorado",2122a0,"iron, gold, silver, and other metal ores","[21221, 21222, 21229]",0.000,2670.0,10099,0.000000,...,0,0,0,0,0,0,0,0,0,0
4,8001,1,"Adams County, Colorado",212310,dimensional stone,[21231],0.000,2385.0,8559,0.000000,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306027,32510,510,"Carson City, Nevada",812300,dry-cleaning and laundry,[8123],0.000,7516.0,11735,0.000000,...,0,0,0,0,0,0,0,0,0,0
306028,32510,510,"Carson City, Nevada",812900,"pet care, photofinishing, parking and other su...",[8129],0.331,15275.0,16196,0.000351,...,1.56924E-08,0,0.00227838,0,1.39959E-10,3.05365E-12,2.71419E-05,8.10484E-05,0.203401573,0.000102408
306029,32510,510,"Carson City, Nevada",813100,religious organizations,[8131],2.441,15995.0,34235,0.005225,...,3.5744E-10,0,0.01400192,0,0,0,0,0.000669559,1.490564525,0.005461919
306030,32510,510,"Carson City, Nevada",813a00,"grantmaking, giving, and social advocacy organ...","[8132, 8133]",0.635,12255.0,21646,0.001122,...,1.436E-11,0,0.008325978,0,0,0,0,3.56898E-05,0.777639617,9.07612E-05
306031,32510,510,"Carson City, Nevada",813b00,"civic, social, professional, and similar organ...","[8134, 8139]",3.487,22449.0,29800,0.004629,...,3.11952E-10,0,0.054858658,0,3.6505E-12,0,4.77527E-07,0.000716243,3.605601773,0.007700563

In [25]:
# Number of available fips codes
len(industry_data['fips'].unique())

3140

### Finding out diffrerences in "fips" values between the two datasets
Check the counties_fips.csv file in data_raw to find out if fips value actually corresponds to a county or if it corresponds to a state of national value.

In [26]:
industry_fips = set(industry_data['fips'].unique())
cancer_fips = set(cancer_data['fips'].unique())

#### Getting "fips" values in cancer data that don't have corresponding industry data and the other way around

In [27]:
cancer_diff_industry = cancer_fips.difference(industry_fips)
print(cancer_diff_industry)

{0, 48000, 32000, 16000, 53000, 37000, 21000, 5000, 48269, 42000, 26000, 10000, 47000, 2201, 31000, 15000, 15005, 36000, 20000, 4000, 41000, 25000, 9000, 46000, 30000, 51000, 2232, 35000, 19000, 56000, 40000, 24000, 8000, 45000, 29000, 13000, 51917, 50000, 34000, 18000, 2900, 55000, 39000, 23000, 44000, 28000, 12000, 33000, 17000, 1000, 2280, 49000, 54000, 38000, 22000, 6000, 27000}

In [28]:
county_corresp_fips = pd.read_csv('../data_raw/counties_fips.csv')

In [29]:
county_corresp_fips.head()

   FIPS     Name State
0  1001  Autauga    AL
1  1003  Baldwin    AL
2  1005  Barbour    AL
3  1007     Bibb    AL
4  1009   Blount    AL

In [30]:
# getting fips values which correspond to actual counties but don't have entries in the industry dataset
missing_industry_values = set()
for fips in cancer_diff_industry:
    if not county_corresp_fips[county_corresp_fips['FIPS'] == fips].empty:
        missing_industry_values.add(fips)
print(missing_industry_values)

{2232, 2201, 2280, 48269}

In [31]:
industry_diff_cancer = industry_fips.difference(cancer_fips)
len(industry_diff_cancer)

7

In [32]:
#getting fips values that don't correspond to actual counties but have entries in the industry dataset
extra_industry_values = set()
for fips in industry_diff_cancer:
    if county_corresp_fips[county_corresp_fips['FIPS'] == fips].empty:
        extra_industry_values.add(fips)
print(extra_industry_values)

{2275, 2195, 2198, 2230, 2105}

### Aggregate factors for fips

In [33]:
industryData=industry_data[['fips','ACID', 'ENRG', 'ETOX',
       'EUTR', 'FOOD', 'GCC', 'HAPS', 'HAZW', 'HC', 'HNC', 'HRSP', 'HTOX',
       'JOBS', 'LAND', 'METL', 'MINE', 'MSW', 'NREN', 'OZON', 'PEST', 'REN',
       'SMOG', 'VADD', 'WATR']]

for i in ['fips','ACID', 'ENRG', 'ETOX',
       'EUTR', 'FOOD', 'GCC', 'HAPS', 'HAZW', 'HC', 'HNC', 'HRSP', 'HTOX',
       'JOBS', 'LAND', 'METL', 'MINE', 'MSW', 'NREN', 'OZON', 'PEST', 'REN',
       'SMOG', 'VADD', 'WATR']:
    industryData[i] = industryData[i].astype("float64")
industryData=industryData.groupby(['fips']).sum()
industryData

C:\Users\Owner\Miniconda3\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.

,ACID,ENRG,ETOX,EUTR,FOOD,GCC,HAPS,HAZW,HC,HNC,...,METL,MINE,MSW,NREN,OZON,PEST,REN,SMOG,VADD,WATR
fips,,,,,,,,,,,,,,,,,,,,,
1001.0,1.049800,2609.156621,3.932211,0.091967,1.070762,375.880086,0.028596,0.038196,1.392760e-08,6.838210e-08,...,0.000177,0.000000,3.332971,1558.288943,8.205763e-06,6.937696e-05,1050.867678,9.764524,168.936475,27.485562
1003.0,0.280475,15.561882,7.987962,0.290754,7.601684,121.748265,0.062129,0.932868,5.461040e-08,2.547902e-07,...,0.000130,44.123480,28.367361,12.236171,1.025729e-05,1.910217e-04,3.325711,9.430919,1620.234233,4.251408
1005.0,0.210885,0.010255,4.445820,0.027651,0.184201,41.021013,0.014290,0.006247,3.207004e-08,1.300874e-07,...,0.000007,0.000000,1.000043,0.000000,2.608045e-07,5.804013e-05,0.010255,7.502860,65.168132,0.701977
1007.0,0.059937,30.656456,2.418462,0.009070,0.112118,11.566748,0.004779,0.007600,9.819009e-09,5.424299e-08,...,0.000010,0.000000,0.520036,0.000000,8.704410e-07,3.238827e-05,30.656456,2.133152,24.050294,0.384009
1009.0,0.066937,0.017388,0.668729,0.008988,0.313152,13.374711,0.006907,0.014673,1.074744e-08,4.555526e-08,...,0.000009,0.000000,1.277899,0.000000,4.780418e-06,1.113430e-05,0.017388,2.409639,60.574602,0.160868
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56037.0,1.288242,6846.474113,1.671191,0.242657,1.548135,468.448494,0.094393,0.074211,2.360126e-07,1.372274e-06,...,0.000158,3197.779327,6.811835,6844.091086,6.462275e-06,1.788926e-05,2.383027,41.472524,654.507956,15.008485
56039.0,0.083954,1.400183,17.679180,0.056704,3.572117,47.566459,0.090532,0.267253,3.504199e-08,1.471061e-07,...,0.000049,0.010181,12.942471,0.656189,5.078643e-06,4.713616e-04,0.743994,3.222444,721.506003,4.511225
56041.0,0.192684,3509.922266,0.227323,0.027889,0.588789,62.957404,0.020252,0.015144,3.722919e-08,2.226537e-07,...,0.000022,730.743964,2.413328,3509.893777,1.139964e-06,1.078417e-06,0.028489,6.938709,202.008187,1.091574
56043.0,0.084944,1652.835530,0.073477,0.012313,0.141232,17.695252,0.008530,0.004346,1.659289e-08,8.460836e-08,...,0.000001,0.000000,0.774102,1652.832375,3.911731e-07,5.269024e-10,0.003155,3.325439,51.721583,0.083898
56045.0,0.091856,1972.064340,0.166077,0.013064,0.136889,21.413600,0.009921,0.003162,2.299176e-08,1.369677e-07,...,0.000002,31.285543,0.491881,1971.904410,8.367255e-07,2.198150e-06,0.159930,3.642929,28.875893,0.122450

### Joining datasets on "fips" column

#### Inner join: Only keep fips values that are in both datasets

In [34]:
df_inner = pd.merge(cancer_data, industryData, on='fips', how='inner')

In [35]:
len(df_inner["fips"].unique())

3133

In [36]:
df_inner

,locale,fips,areatype,cancer,stateFIPS,state,cancer_description,annual_count_avg,incidence rate_per_100000,incidence rate_lower_95_confidence,...,METL,MINE,MSW,NREN,OZON,PEST,REN,SMOG,VADD,WATR
0,"Autauga County(6,10)",1001,county,1,1,alabama,All Cancer Sites,304,495.6,470.6,...,0.000177,0.000000,3.332971,1558.288943,8.205763e-06,0.000069,1050.867678,9.764524,168.936475,27.485562
1,"Autauga County(6,10)",1001,county,3,1,alabama,Oral Cavity & Pharynx,8,13.5,9.6,...,0.000177,0.000000,3.332971,1558.288943,8.205763e-06,0.000069,1050.867678,9.764524,168.936475,27.485562
2,"Autauga County(6,10)",1001,county,17,1,alabama,Esophagus,0,0.0,0.0,...,0.000177,0.000000,3.332971,1558.288943,8.205763e-06,0.000069,1050.867678,9.764524,168.936475,27.485562
3,"Autauga County(6,10)",1001,county,18,1,alabama,Stomach,6,9.1,6.0,...,0.000177,0.000000,3.332971,1558.288943,8.205763e-06,0.000069,1050.867678,9.764524,168.936475,27.485562
4,"Autauga County(6,10)",1001,county,20,1,alabama,Colon & Rectum,32,52.2,44.2,...,0.000177,0.000000,3.332971,1558.288943,8.205763e-06,0.000069,1050.867678,9.764524,168.936475,27.485562
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72054,"Weston County(6,10)",56045,county,86,56,wyoming,Non-Hodgkin Lymphoma,0,0.0,0.0,...,0.000002,31.285543,0.491881,1971.904410,8.367255e-07,0.000002,0.159930,3.642929,28.875893,0.122450
72055,"Weston County(6,10)",56045,county,90,56,wyoming,Leukemia,0,0.0,0.0,...,0.000002,31.285543,0.491881,1971.904410,8.367255e-07,0.000002,0.159930,3.642929,28.875893,0.122450
72056,"Weston County(6,10)",56045,county,400,56,wyoming,Breast (in situ) (Female),0,0.0,0.0,...,0.000002,31.285543,0.491881,1971.904410,8.367255e-07,0.000002,0.159930,3.642929,28.875893,0.122450
72057,"Weston County(6,10)",56045,county,515,56,wyoming,"Childhood (Ages <20, All Sites)",0,0.0,0.0,...,0.000002,31.285543,0.491881,1971.904410,8.367255e-07,0.000002,0.159930,3.642929,28.875893,0.122450
72058,"Weston County(6,10)",56045,county,516,56,wyoming,"Childhood (Ages <15, All Sites)",0,0.0,0.0,...,0.000002,31.285543,0.491881,1971.904410,8.367255e-07,0.000002,0.159930,3.642929,28.875893,0.122450

### Exporting the joined dataset
For now we'll work with the resulting inner_join data because it is the most complete.

In [37]:
df_inner.to_csv("./data_clean/cancer_industry.csv", index=False)